# Generated by Django 3.1.14 on 2023-07-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorprogram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='name',
            new_name='title',
        ),
    ]
