# Generated by Django 3.1.14 on 2023-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorprogram', '0003_auto_20230714_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='id_user',
            field=models.IntegerField(default=None, verbose_name='id_user'),
        ),
    ]
